// Generated by @commercelayer/cli-generator from gen.config.ts: do not edit by hand.
import { runCommand } from '@oclif/test'
import { expect } from 'chai'
import { AUTH, api, resource, single, useMockedApi } from '../../helpers'

describe('gift_card:deactivate', () => {
  useMockedApi()

  it('sends the _deactivate trigger', async function () {
    this.timeout(15000)
    api()
      .get('/api/gift_cards/rEs1')
      .reply(200, single(resource('gift_cards', 'rEs1')))
      .patch('/api/gift_cards/rEs1', (body) => body.data.attributes._deactivate === true)
      .reply(200, single(resource('gift_cards', 'rEs1')))
    const ctx = await runCommand(['gift_card:deactivate', 'rEs1', ...AUTH])
    if (ctx.error) throw ctx.error
    expect(ctx.stdout).to.contain('Action deactivate executed without errors')
    expect(ctx.stdout).to.contain('rEs1')
  })
})
