// Generated by @commercelayer/cli-generator from gen.config.ts: do not edit by hand.
import { expect, test } from '@oclif/test'
import { AUTH, api, resource, single, useMockedApi } from '../../helpers'

describe('gift_card:remove_tags', () => {
  useMockedApi()

  test
    .timeout(15000)
    .do(() => {
      api()
        .get('/api/gift_cards/rEs1')
        .reply(200, single(resource('gift_cards', 'rEs1')))
        .patch('/api/gift_cards/rEs1', (body) => body.data.attributes._remove_tags === true)
        .reply(200, single(resource('gift_cards', 'rEs1')))
    })
    .stdout()
    .command(['gift_card:remove_tags', 'rEs1', ...AUTH])
    .it('sends the _remove_tags trigger', (ctx) => {
      expect(ctx.stdout).to.contain('Action remove_tags executed without errors')
      expect(ctx.stdout).to.contain('rEs1')
    })
})
