import { expect } from 'chai'
import { labelerConfig } from '../src/commands/labels.ts'
import { surfaceDiff } from '../src/commands/manifest.ts'
import { withMaintenanceNote } from '../src/commands/notes.ts'
import { dependenciesToPublish } from '../src/commands/publish.ts'
import { withWorkspaceDeps } from '../src/commands/try.ts'
import { addChangedDependencies, bump } from '../src/commands/version.ts'
import { pkg } from './helpers.ts'

describe('version', () => {
  it('bumps by level', () => {
    expect(bump('6.9.9', 'patch')).to.equal('6.9.10')
    expect(bump('6.9.9', 'minor')).to.equal('6.10.0')
    expect(bump('6.9.9', 'major')).to.equal('7.0.0')
  })
  it('releases a prerelease left in a package.json as its stable version', () => {
    expect(bump('7.0.0-beta.1', 'patch')).to.equal('7.0.0')
    expect(bump('7.0.0-beta.1', 'major')).to.equal('7.0.0')
  })

  it('adds the changed workspace dependencies of the selected packages, transitively', () => {
    const core = pkg('core', '6.0.0')
    const ux = pkg('ux', '2.0.0', ['core'])
    const tags = pkg('tags', '3.0.0', ['ux'])
    const other = pkg('other', '1.0.0')
    const candidate = (p: typeof core, next: string) => ({ pkg: p, commits: [['fix: x']], level: 'patch' as const, why: '', next })
    const candidates = [candidate(core, '6.0.1'), candidate(ux, '2.0.1'), candidate(tags, '3.0.1'), candidate(other, '1.0.1')]
    const selected = [{ ...candidates[2], version: '3.1.0' }]
    const added = addChangedDependencies(selected, candidates)
    expect(selected.map((s) => `${s.pkg.dir}@${s.version}`)).to.deep.equal(['tags@3.1.0', 'ux@2.0.1', 'core@6.0.1'])
    expect(added.map((a) => `${a.added.pkg.dir}<-${a.by.pkg.dir}`)).to.deep.equal(['ux<-tags', 'core<-ux'])
  })
})

describe('publish', () => {
  const core = pkg('core', '6.0.0')
  const ux = pkg('ux', '2.0.0', ['core'])
  const tags = pkg('tags', '3.0.0', ['core', 'ux'])
  const packages = [core, ux, tags]

  it('publishes the dependencies not on npm first', () => {
    const deps = dependenciesToPublish(tags, packages, { published: () => false, tags: new Set(['core-v6.0.0', 'ux-v2.0.0']) })
    expect(deps.map((p) => p.dir)).to.deep.equal(['core', 'ux'])
  })
  it('skips the dependencies already on npm', () => {
    const deps = dependenciesToPublish(tags, packages, { published: (p) => p.dir === 'core', tags: new Set(['ux-v2.0.0']) })
    expect(deps.map((p) => p.dir)).to.deep.equal(['ux'])
  })
  it('stops on a dependency without a release tag', () => {
    expect(() => dependenciesToPublish(tags, packages, { published: () => false, tags: new Set(['ux-v2.0.0']) })).to.throw(/@cl\/tags needs @cl\/core@6.0.0.*no core-v6.0.0 release tag/)
  })
  it('stops on a private dependency', () => {
    const dev = pkg('dev', '1.0.0', [], { private: true })
    expect(() => dependenciesToPublish(pkg('x', '1.0.0', ['dev']), [dev], { published: () => false, tags: new Set() })).to.throw(/private @cl\/dev/)
  })
})

describe('manifest', () => {
  it('reports removed and added commands, flags and args', () => {
    const previous = { commands: { a: { flags: { x: {}, y: {} }, args: { id: {} } }, gone: {} } }
    const current = { commands: { a: { flags: { x: {}, z: {} }, args: {} }, fresh: {} } }
    expect(surfaceDiff(previous, current)).to.deep.equal({
      removed: ['flag a --y', 'arg a id', 'command gone'],
      added: ['flag a --z', 'command fresh'],
    })
  })
})

describe('notes', () => {
  it('adds a maintenance note when no section is shown', () => {
    expect(withMaintenanceNote('## 1.0.1', 'x-v1.0.0')).to.match(/Maintenance release: no changes to features or fixes since x-v1.0.0/)
    expect(withMaintenanceNote('## 1.1.0\n\n### Features\n\n* a', 'x-v1.0.0')).to.not.match(/Maintenance/)
  })
})

describe('labels', () => {
  it('has one pkg:<dir> label per package', () => {
    const config = labelerConfig([{ dir: 'tags', path: 'plugins/tags' }])
    expect(config).to.match(/^# Generated by/)
    expect(config).to.contain("'pkg:tags':\n  - changed-files:\n      - any-glob-to-any-file:\n          - 'plugins/tags/**'\n")
  })
})

describe('try', () => {
  it('installs the workspace dependencies of the chosen packages', () => {
    const core = pkg('core', '1.0.0')
    const ux = pkg('ux', '1.0.0', ['core'])
    const tags = pkg('tags', '1.0.0', ['ux'])
    const orders = pkg('orders', '1.0.0', ['core'])
    expect([...withWorkspaceDeps([tags], [core, ux, tags, orders])].map((p) => p.dir)).to.deep.equal(['tags', 'ux', 'core'])
  })
})
