// Generated by @commercelayer/cli-generator from gen.config.ts: do not edit by hand.
import { runCommand } from '@oclif/test'
import { expect } from 'chai'
import { AUTH, api, resource, single, useMockedApi } from '../../helpers'

describe('bundle:compute_compare_at_amount', () => {
  useMockedApi()

  it('sends the _compute_compare_at_amount trigger', async function () {
    this.timeout(15000)
    api()
      .get('/api/bundles/rEs1')
      .reply(200, single(resource('bundles', 'rEs1')))
      .patch('/api/bundles/rEs1', (body) => body.data.attributes._compute_compare_at_amount === true)
      .reply(200, single(resource('bundles', 'rEs1')))
    const ctx = await runCommand(['bundle:compute_compare_at_amount', 'rEs1', ...AUTH])
    if (ctx.error) throw ctx.error
    expect(ctx.stdout).to.contain('Action compute_compare_at_amount executed without errors')
    expect(ctx.stdout).to.contain('rEs1')
  })
})
