// Generated by @commercelayer/cli-generator from gen.config.ts: do not edit by hand.
import { expect, test } from '@oclif/test'
import { AUTH, api, resource, single, useMockedApi } from '../../helpers'

describe('bundle:compute_compare_at_amount', () => {
  useMockedApi()

  test
    .timeout(15000)
    .do(() => {
      api()
        .get('/api/bundles/rEs1')
        .reply(200, single(resource('bundles', 'rEs1')))
        .patch('/api/bundles/rEs1', (body) => body.data.attributes._compute_compare_at_amount === true)
        .reply(200, single(resource('bundles', 'rEs1')))
    })
    .stdout()
    .command(['bundle:compute_compare_at_amount', 'rEs1', ...AUTH])
    .it('sends the _compute_compare_at_amount trigger', (ctx) => {
      expect(ctx.stdout).to.contain('Action compute_compare_at_amount executed without errors')
      expect(ctx.stdout).to.contain('rEs1')
    })
})
