// Generated by @commercelayer/cli-generator from gen.config.ts: do not edit by hand.
import { runCommand } from '@oclif/test'
import { expect } from 'chai'
import { AUTH, api, resource, single, useMockedApi } from '../../helpers'

describe('adyen_gateway:check', () => {
  useMockedApi()

  it('sends the _check trigger', async function () {
    this.timeout(15000)
    api()
      .get('/api/adyen_gateways/rEs1')
      .reply(200, single(resource('adyen_gateways', 'rEs1')))
      .patch('/api/adyen_gateways/rEs1', (body) => body.data.attributes._check === true)
      .reply(200, single(resource('adyen_gateways', 'rEs1')))
    const ctx = await runCommand(['adyen_gateway:check', 'rEs1', ...AUTH])
    if (ctx.error) throw ctx.error
    expect(ctx.stdout).to.contain('Action check executed without errors')
    expect(ctx.stdout).to.contain('rEs1')
  })
})
