// Generated by @commercelayer/cli-generator from gen.config.ts: do not edit by hand.
import { expect, test } from '@oclif/test'
import { AUTH, api, resource, single, useMockedApi } from '../../helpers'

describe('adyen_gateway:check', () => {
  useMockedApi()

  test
    .timeout(15000)
    .do(() => {
      api()
        .get('/api/adyen_gateways/rEs1')
        .reply(200, single(resource('adyen_gateways', 'rEs1')))
        .patch('/api/adyen_gateways/rEs1', (body) => body.data.attributes._check === true)
        .reply(200, single(resource('adyen_gateways', 'rEs1')))
    })
    .stdout()
    .command(['adyen_gateway:check', 'rEs1', ...AUTH])
    .it('sends the _check trigger', (ctx) => {
      expect(ctx.stdout).to.contain('Action check executed without errors')
      expect(ctx.stdout).to.contain('rEs1')
    })
})
