// Generated by @commercelayer/cli-generator from gen.config.ts: do not edit by hand.
import { expect, test } from '@oclif/test'
import { AUTH, api, resource, single, useMockedApi } from '../../helpers'

describe('stripe_gateway:update_webhooks', () => {
  useMockedApi()

  test
    .timeout(15000)
    .do(() => {
      api()
        .get('/api/stripe_gateways/rEs1')
        .reply(200, single(resource('stripe_gateways', 'rEs1')))
        .patch('/api/stripe_gateways/rEs1', (body) => body.data.attributes._update_webhooks === true)
        .reply(200, single(resource('stripe_gateways', 'rEs1')))
    })
    .stdout()
    .command(['stripe_gateway:update_webhooks', 'rEs1', ...AUTH])
    .it('sends the _update_webhooks trigger', (ctx) => {
      expect(ctx.stdout).to.contain('Action update_webhooks executed without errors')
      expect(ctx.stdout).to.contain('rEs1')
    })
})
