// Generated by @commercelayer/cli-generator from gen.config.ts: do not edit by hand.
import { expect, test } from '@oclif/test'
import { AUTH, api, resource, single, useMockedApi } from '../../helpers'

describe('checkout_com_gateway:refresh_webhook_secrets', () => {
  useMockedApi()

  test
    .timeout(15000)
    .do(() => {
      api()
        .get('/api/checkout_com_gateways/rEs1')
        .reply(200, single(resource('checkout_com_gateways', 'rEs1')))
        .patch('/api/checkout_com_gateways/rEs1', (body) => body.data.attributes._refresh_webhook_secrets === true)
        .reply(200, single(resource('checkout_com_gateways', 'rEs1')))
    })
    .stdout()
    .command(['checkout_com_gateway:refresh_webhook_secrets', 'rEs1', ...AUTH])
    .it('sends the _refresh_webhook_secrets trigger', (ctx) => {
      expect(ctx.stdout).to.contain('Action refresh_webhook_secrets executed without errors')
      expect(ctx.stdout).to.contain('rEs1')
    })
})
