// Generated by @commercelayer/cli-generator from gen.config.ts: do not edit by hand.
import { runCommand } from '@oclif/test'
import { expect } from 'chai'
import { AUTH, api, resource, single, useMockedApi } from '../../helpers'

describe('shipment:get_rates', () => {
  useMockedApi()

  it('sends the _get_rates trigger', async function () {
    this.timeout(15000)
    api()
      .get('/api/shipments/rEs1')
      .reply(200, single(resource('shipments', 'rEs1')))
      .patch('/api/shipments/rEs1', (body) => body.data.attributes._get_rates === true)
      .reply(200, single(resource('shipments', 'rEs1')))
    const ctx = await runCommand(['shipment:get_rates', 'rEs1', ...AUTH])
    if (ctx.error) throw ctx.error
    expect(ctx.stdout).to.contain('Action get_rates executed without errors')
    expect(ctx.stdout).to.contain('rEs1')
  })
})
