// Generated by @commercelayer/cli-generator from gen.config.ts: do not edit by hand.
import { expect, test } from '@oclif/test'
import { AUTH, api, resource, single, useMockedApi } from '../../helpers'

describe('shipment:purchase', () => {
  useMockedApi()

  test
    .timeout(15000)
    .do(() => {
      api()
        .get('/api/shipments/rEs1')
        .reply(200, single(resource('shipments', 'rEs1')))
        .patch('/api/shipments/rEs1', (body) => body.data.attributes._purchase === true)
        .reply(200, single(resource('shipments', 'rEs1')))
    })
    .stdout()
    .command(['shipment:purchase', 'rEs1', ...AUTH])
    .it('sends the _purchase trigger', (ctx) => {
      expect(ctx.stdout).to.contain('Action purchase executed without errors')
      expect(ctx.stdout).to.contain('rEs1')
    })
})
