overrides:
  brace-expansion@<1.1.13: '>=1.1.13'
  brace-expansion@>=2.0.0 <2.0.3: '>=2.0.3'
  handlebars@>=4.0.0 <4.7.9: '>=4.7.9'
  handlebars@>=4.0.0 <=4.7.8: '>=4.7.9'
  handlebars@>=4.6.0 <=4.7.8: '>=4.7.9'
