// Generated by @commercelayer/cli-generator from gen.config.ts: do not edit by hand.
import { runCommand } from '@oclif/test'
import { expect } from 'chai'
import { AUTH, api, resource, single, useMockedApi } from '../../helpers'

describe('stock_line_item:decrement_stock', () => {
  useMockedApi()

  it('sends the _decrement_stock trigger', async function () {
    this.timeout(15000)
    api()
      .get('/api/stock_line_items/rEs1')
      .reply(200, single(resource('stock_line_items', 'rEs1')))
      .patch('/api/stock_line_items/rEs1', (body) => body.data.attributes._decrement_stock === true)
      .reply(200, single(resource('stock_line_items', 'rEs1')))
    const ctx = await runCommand(['stock_line_item:decrement_stock', 'rEs1', ...AUTH])
    if (ctx.error) throw ctx.error
    expect(ctx.stdout).to.contain('Action decrement_stock executed without errors')
    expect(ctx.stdout).to.contain('rEs1')
  })
})
