// Generated by @commercelayer/cli-generator from gen.config.ts: do not edit by hand.
import { expect, test } from '@oclif/test'
import { AUTH, api, resource, single, useMockedApi } from '../../helpers'

describe('stock_line_item:release_stock', () => {
  useMockedApi()

  test
    .timeout(15000)
    .do(() => {
      api()
        .get('/api/stock_line_items/rEs1')
        .reply(200, single(resource('stock_line_items', 'rEs1')))
        .patch('/api/stock_line_items/rEs1', (body) => body.data.attributes._release_stock === true)
        .reply(200, single(resource('stock_line_items', 'rEs1')))
    })
    .stdout()
    .command(['stock_line_item:release_stock', 'rEs1', ...AUTH])
    .it('sends the _release_stock trigger', (ctx) => {
      expect(ctx.stdout).to.contain('Action release_stock executed without errors')
      expect(ctx.stdout).to.contain('rEs1')
    })
})
