// Generated by @commercelayer/cli-generator from gen.config.ts: do not edit by hand.
import { runCommand } from '@oclif/test'
import { expect } from 'chai'
import { AUTH, api, resource, single, useMockedApi } from '../../helpers'

describe('paypal_payment:refresh', () => {
  useMockedApi()

  it('sends the _refresh trigger', async function () {
    this.timeout(15000)
    api()
      .get('/api/paypal_payments/rEs1')
      .reply(200, single(resource('paypal_payments', 'rEs1')))
      .patch('/api/paypal_payments/rEs1', (body) => body.data.attributes._refresh === true)
      .reply(200, single(resource('paypal_payments', 'rEs1')))
    const ctx = await runCommand(['paypal_payment:refresh', 'rEs1', ...AUTH])
    if (ctx.error) throw ctx.error
    expect(ctx.stdout).to.contain('Action refresh executed without errors')
    expect(ctx.stdout).to.contain('rEs1')
  })
})
