// Generated by @commercelayer/cli-generator from gen.config.ts: do not edit by hand.
import { runCommand } from '@oclif/test'
import { expect } from 'chai'
import { AUTH, api, resource, single, useMockedApi } from '../../helpers'

describe('free_shipping_promotion:disable', () => {
  useMockedApi()

  it('sends the _disable trigger', async function () {
    this.timeout(15000)
    api()
      .get('/api/free_shipping_promotions/rEs1')
      .reply(200, single(resource('free_shipping_promotions', 'rEs1')))
      .patch('/api/free_shipping_promotions/rEs1', (body) => body.data.attributes._disable === true)
      .reply(200, single(resource('free_shipping_promotions', 'rEs1')))
    const ctx = await runCommand(['free_shipping_promotion:disable', 'rEs1', ...AUTH])
    if (ctx.error) throw ctx.error
    expect(ctx.stdout).to.contain('Action disable executed without errors')
    expect(ctx.stdout).to.contain('rEs1')
  })
})
