// Generated by @commercelayer/cli-generator from gen.config.ts: do not edit by hand.
import { expect, test } from '@oclif/test'
import { AUTH, api, resource, single, useMockedApi } from '../../helpers'

describe('link:enable', () => {
  useMockedApi()

  test
    .timeout(15000)
    .do(() => {
      api()
        .get('/api/links/rEs1')
        .reply(200, single(resource('links', 'rEs1')))
        .patch('/api/links/rEs1', (body) => body.data.attributes._enable === true)
        .reply(200, single(resource('links', 'rEs1')))
    })
    .stdout()
    .command(['link:enable', 'rEs1', ...AUTH])
    .it('sends the _enable trigger', (ctx) => {
      expect(ctx.stdout).to.contain('Action enable executed without errors')
      expect(ctx.stdout).to.contain('rEs1')
    })
})
