// Generated by @commercelayer/cli-generator from gen.config.ts: do not edit by hand.
import { expect, test } from '@oclif/test'
import { AUTH, api, resource, single, useMockedApi } from '../../helpers'

describe('return:request', () => {
  useMockedApi()

  test
    .timeout(15000)
    .do(() => {
      api()
        .get('/api/returns/rEs1')
        .reply(200, single(resource('returns', 'rEs1')))
        .patch('/api/returns/rEs1', (body) => body.data.attributes._request === true)
        .reply(200, single(resource('returns', 'rEs1')))
    })
    .stdout()
    .command(['return:request', 'rEs1', ...AUTH])
    .it('sends the _request trigger', (ctx) => {
      expect(ctx.stdout).to.contain('Action request executed without errors')
      expect(ctx.stdout).to.contain('rEs1')
    })
})
