// Generated by @commercelayer/cli-generator from gen.config.ts: do not edit by hand.
import { runCommand } from '@oclif/test'
import { expect } from 'chai'
import { AUTH, api, resource, single, useMockedApi } from '../../helpers'

describe('return:unarchive', () => {
  useMockedApi()

  it('sends the _unarchive trigger', async function () {
    this.timeout(15000)
    api()
      .get('/api/returns/rEs1')
      .reply(200, single(resource('returns', 'rEs1')))
      .patch('/api/returns/rEs1', (body) => body.data.attributes._unarchive === true)
      .reply(200, single(resource('returns', 'rEs1')))
    const ctx = await runCommand(['return:unarchive', 'rEs1', ...AUTH])
    if (ctx.error) throw ctx.error
    expect(ctx.stdout).to.contain('Action unarchive executed without errors')
    expect(ctx.stdout).to.contain('rEs1')
  })
})
