// Generated by @commercelayer/cli-generator from gen.config.ts: do not edit by hand.
import { runCommand } from '@oclif/test'
import { expect } from 'chai'
import { AUTH, api, resource, single, useMockedApi } from '../../helpers'

describe('orders:authorize', () => {
  useMockedApi()

  it('sends the _authorize trigger', async function () {
    this.timeout(15000)
    api()
      .get('/api/orders/oRd1')
      .query(true)
      .reply(200, single(resource('orders', 'oRd1')))
      .patch('/api/orders/oRd1', (body) => body.data.attributes._authorize === true)
      .query(true)
      .reply(200, single(resource('orders', 'oRd1')))
    const ctx = await runCommand(['orders:authorize', 'oRd1', ...AUTH])
    if (ctx.error) throw ctx.error
    expect(ctx.stdout).to.contain('Action authorize executed without errors on order oRd1')
  })
})
