// Generated by @commercelayer/cli-generator from gen.config.ts: do not edit by hand.
import { expect, test } from '@oclif/test'
import { AUTH, api, resource, single, useMockedApi } from '../../helpers'

describe('orders:customer_payment_source_id', () => {
  useMockedApi()

  test
    .timeout(15000)
    .do(() => {
      api()
        .get('/api/orders/oRd1')
        .query(true)
        .reply(200, single(resource('orders', 'oRd1')))
        .patch('/api/orders/oRd1', (body) => body.data.attributes._customer_payment_source_id === 'vAlUe1')
        .query(true)
        .reply(200, single(resource('orders', 'oRd1')))
    })
    .stdout()
    .command(['orders:customer_payment_source_id', 'oRd1', ...AUTH, '-v', 'vAlUe1'])
    .it('sends the _customer_payment_source_id trigger', (ctx) => {
      expect(ctx.stdout).to.contain('Action customer_payment_source_id executed without errors on order oRd1')
    })
})
