// Generated by @commercelayer/cli-generator from gen.config.ts: do not edit by hand.
import { expect, test } from '@oclif/test'
import { AUTH, api, resource, single, useMockedApi } from '../../helpers'

describe('orders:fix_payment_source', () => {
  useMockedApi()

  test
    .timeout(15000)
    .do(() => {
      api()
        .get('/api/orders/oRd1')
        .query(true)
        .reply(200, single(resource('orders', 'oRd1')))
        .patch('/api/orders/oRd1', (body) => body.data.attributes._fix_payment_source === true)
        .query(true)
        .reply(200, single(resource('orders', 'oRd1')))
    })
    .stdout()
    .command(['orders:fix_payment_source', 'oRd1', ...AUTH])
    .it('sends the _fix_payment_source trigger', (ctx) => {
      expect(ctx.stdout).to.contain('Action fix_payment_source executed without errors on order oRd1')
    })
})
