// Generated by @commercelayer/cli-generator from gen.config.ts: do not edit by hand.
import { runCommand } from '@oclif/test'
import { expect } from 'chai'
import { AUTH, api, resource, single, useMockedApi } from '../../helpers'

describe('orders:reset_circuit', () => {
  useMockedApi()

  it('sends the _reset_circuit trigger', async function () {
    this.timeout(15000)
    api()
      .get('/api/orders/oRd1')
      .query(true)
      .reply(200, single(resource('orders', 'oRd1')))
      .patch('/api/orders/oRd1', (body) => body.data.attributes._reset_circuit === true)
      .query(true)
      .reply(200, single(resource('orders', 'oRd1')))
    const ctx = await runCommand(['orders:reset_circuit', 'oRd1', ...AUTH])
    if (ctx.error) throw ctx.error
    expect(ctx.stdout).to.contain('Action reset_circuit executed without errors on order oRd1')
  })
})
