// Generated by @commercelayer/cli-generator from gen.config.ts: do not edit by hand.
import { expect, test } from '@oclif/test'
import { AUTH, api, resource, single, useMockedApi } from '../../helpers'

describe('orders:save_shipping_address_to_customer_address_book', () => {
  useMockedApi()

  test
    .timeout(15000)
    .do(() => {
      api()
        .get('/api/orders/oRd1')
        .query(true)
        .reply(200, single(resource('orders', 'oRd1')))
        .patch('/api/orders/oRd1', (body) => body.data.attributes._save_shipping_address_to_customer_address_book === true)
        .query(true)
        .reply(200, single(resource('orders', 'oRd1')))
    })
    .stdout()
    .command(['orders:save_shipping_address_to_customer_address_book', 'oRd1', ...AUTH])
    .it('sends the _save_shipping_address_to_customer_address_book trigger', (ctx) => {
      expect(ctx.stdout).to.contain('Action save_shipping_address_to_customer_address_book executed without errors on order oRd1')
    })
})
