// Generated by @commercelayer/cli-generator from gen.config.ts: do not edit by hand.
import { runCommand } from '@oclif/test'
import { expect } from 'chai'
import { AUTH, api, resource, single, useMockedApi } from '../../helpers'

describe('orders:shipping_address_clone_id', () => {
  useMockedApi()

  it('sends the _shipping_address_clone_id trigger', async function () {
    this.timeout(15000)
    api()
      .get('/api/orders/oRd1')
      .query(true)
      .reply(200, single(resource('orders', 'oRd1')))
      .patch('/api/orders/oRd1', (body) => body.data.attributes._shipping_address_clone_id === 'vAlUe1')
      .query(true)
      .reply(200, single(resource('orders', 'oRd1')))
    const ctx = await runCommand(['orders:shipping_address_clone_id', 'oRd1', ...AUTH, '-v', 'vAlUe1'])
    if (ctx.error) throw ctx.error
    expect(ctx.stdout).to.contain('Action shipping_address_clone_id executed without errors on order oRd1')
  })
})
