// Generated by @commercelayer/cli-generator from gen.config.ts: do not edit by hand.
import { runCommand } from '@oclif/test'
import { expect } from 'chai'
import { AUTH, api, resource, single, useMockedApi } from '../../helpers'

describe('capture:cancel', () => {
  useMockedApi()

  it('sends the _cancel trigger', async function () {
    this.timeout(15000)
    api()
      .get('/api/captures/rEs1')
      .reply(200, single(resource('captures', 'rEs1')))
      .patch('/api/captures/rEs1', (body) => body.data.attributes._cancel === true)
      .reply(200, single(resource('captures', 'rEs1')))
    const ctx = await runCommand(['capture:cancel', 'rEs1', ...AUTH])
    if (ctx.error) throw ctx.error
    expect(ctx.stdout).to.contain('Action cancel executed without errors')
    expect(ctx.stdout).to.contain('rEs1')
  })
})
