// Generated by @commercelayer/cli-generator from gen.config.ts: do not edit by hand.
import { expect, test } from '@oclif/test'
import { AUTH, api, resource, single, useMockedApi } from '../../helpers'

describe('capture:refund_amount_cents', () => {
  useMockedApi()

  test
    .timeout(15000)
    .do(() => {
      api()
        .get('/api/captures/rEs1')
        .reply(200, single(resource('captures', 'rEs1')))
        .patch('/api/captures/rEs1', (body) => body.data.attributes._refund_amount_cents === true)
        .reply(200, single(resource('captures', 'rEs1')))
    })
    .stdout()
    .command(['capture:refund_amount_cents', 'rEs1', ...AUTH])
    .it('sends the _refund_amount_cents trigger', (ctx) => {
      expect(ctx.stdout).to.contain('Action refund_amount_cents executed without errors')
      expect(ctx.stdout).to.contain('rEs1')
    })
})
