// Generated by @commercelayer/cli-generator from gen.config.ts: do not edit by hand.
import { runCommand } from '@oclif/test'
import { expect } from 'chai'
import { AUTH, api, resource, single, useMockedApi } from '../../helpers'

describe('in_stock_subscription:activate', () => {
  useMockedApi()

  it('sends the _activate trigger', async function () {
    this.timeout(15000)
    api()
      .get('/api/in_stock_subscriptions/rEs1')
      .reply(200, single(resource('in_stock_subscriptions', 'rEs1')))
      .patch('/api/in_stock_subscriptions/rEs1', (body) => body.data.attributes._activate === true)
      .reply(200, single(resource('in_stock_subscriptions', 'rEs1')))
    const ctx = await runCommand(['in_stock_subscription:activate', 'rEs1', ...AUTH])
    if (ctx.error) throw ctx.error
    expect(ctx.stdout).to.contain('Action activate executed without errors')
    expect(ctx.stdout).to.contain('rEs1')
  })
})
