// Generated by @commercelayer/cli-generator from gen.config.ts: do not edit by hand.
import { expect, test } from '@oclif/test'
import { AUTH, api, resource, single, useMockedApi } from '../../helpers'

describe('event:trigger', () => {
  useMockedApi()

  test
    .timeout(15000)
    .do(() => {
      api()
        .get('/api/events/rEs1')
        .reply(200, single(resource('events', 'rEs1')))
        .patch('/api/events/rEs1', (body) => body.data.attributes._trigger === true)
        .reply(200, single(resource('events', 'rEs1')))
    })
    .stdout()
    .command(['event:trigger', 'rEs1', ...AUTH])
    .it('sends the _trigger trigger', (ctx) => {
      expect(ctx.stdout).to.contain('Action trigger executed without errors')
      expect(ctx.stdout).to.contain('rEs1')
    })
})
