// Generated by @commercelayer/cli-generator from gen.config.ts: do not edit by hand.
import { runCommand } from '@oclif/test'
import { expect } from 'chai'
import { AUTH, api, resource, single, useMockedApi } from '../../helpers'

describe('event:trigger', () => {
  useMockedApi()

  it('sends the _trigger trigger', async function () {
    this.timeout(15000)
    api()
      .get('/api/events/rEs1')
      .reply(200, single(resource('events', 'rEs1')))
      .patch('/api/events/rEs1', (body) => body.data.attributes._trigger === true)
      .reply(200, single(resource('events', 'rEs1')))
    const ctx = await runCommand(['event:trigger', 'rEs1', ...AUTH])
    if (ctx.error) throw ctx.error
    expect(ctx.stdout).to.contain('Action trigger executed without errors')
    expect(ctx.stdout).to.contain('rEs1')
  })
})
