// Generated by @commercelayer/cli-generator from gen.config.ts: do not edit by hand.
import { expect, test } from '@oclif/test'
import { AUTH, api, resource, single, useMockedApi } from '../../helpers'

describe('external_promotion:reset_circuit', () => {
  useMockedApi()

  test
    .timeout(15000)
    .do(() => {
      api()
        .get('/api/external_promotions/rEs1')
        .reply(200, single(resource('external_promotions', 'rEs1')))
        .patch('/api/external_promotions/rEs1', (body) => body.data.attributes._reset_circuit === true)
        .reply(200, single(resource('external_promotions', 'rEs1')))
    })
    .stdout()
    .command(['external_promotion:reset_circuit', 'rEs1', ...AUTH])
    .it('sends the _reset_circuit trigger', (ctx) => {
      expect(ctx.stdout).to.contain('Action reset_circuit executed without errors')
      expect(ctx.stdout).to.contain('rEs1')
    })
})
