// Generated by @commercelayer/cli-generator from gen.config.ts: do not edit by hand.
import { runCommand } from '@oclif/test'
import { expect } from 'chai'
import { AUTH, api, resource, single, useMockedApi } from '../../helpers'

describe('adyen_payment:details', () => {
  useMockedApi()

  it('sends the _details trigger', async function () {
    this.timeout(15000)
    api()
      .get('/api/adyen_payments/rEs1')
      .reply(200, single(resource('adyen_payments', 'rEs1')))
      .patch('/api/adyen_payments/rEs1', (body) => body.data.attributes._details === true)
      .reply(200, single(resource('adyen_payments', 'rEs1')))
    const ctx = await runCommand(['adyen_payment:details', 'rEs1', ...AUTH])
    if (ctx.error) throw ctx.error
    expect(ctx.stdout).to.contain('Action details executed without errors')
    expect(ctx.stdout).to.contain('rEs1')
  })
})
