// Generated by @commercelayer/cli-generator from gen.config.ts: do not edit by hand.
import { expect, test } from '@oclif/test'
import { AUTH, api, resource, single, useMockedApi } from '../../helpers'

describe('stock_reservation:pending', () => {
  useMockedApi()

  test
    .timeout(15000)
    .do(() => {
      api()
        .get('/api/stock_reservations/rEs1')
        .reply(200, single(resource('stock_reservations', 'rEs1')))
        .patch('/api/stock_reservations/rEs1', (body) => body.data.attributes._pending === true)
        .reply(200, single(resource('stock_reservations', 'rEs1')))
    })
    .stdout()
    .command(['stock_reservation:pending', 'rEs1', ...AUTH])
    .it('sends the _pending trigger', (ctx) => {
      expect(ctx.stdout).to.contain('Action pending executed without errors')
      expect(ctx.stdout).to.contain('rEs1')
    })
})
