// Generated by @commercelayer/cli-generator from gen.config.ts: do not edit by hand.
import { expect, test } from '@oclif/test'
import { AUTH, api, resource, single, useMockedApi } from '../../helpers'

describe('coupon:add_tags', () => {
  useMockedApi()

  test
    .timeout(15000)
    .do(() => {
      api()
        .get('/api/coupons/rEs1')
        .reply(200, single(resource('coupons', 'rEs1')))
        .patch('/api/coupons/rEs1', (body) => body.data.attributes._add_tags === true)
        .reply(200, single(resource('coupons', 'rEs1')))
    })
    .stdout()
    .command(['coupon:add_tags', 'rEs1', ...AUTH])
    .it('sends the _add_tags trigger', (ctx) => {
      expect(ctx.stdout).to.contain('Action add_tags executed without errors')
      expect(ctx.stdout).to.contain('rEs1')
    })
})
