// Generated by @commercelayer/cli-generator from gen.config.ts: do not edit by hand.
import { expect, test } from '@oclif/test'
import { AUTH, api, resource, single, useMockedApi } from '../../helpers'

describe('flex_promotion:disable', () => {
  useMockedApi()

  test
    .timeout(15000)
    .do(() => {
      api()
        .get('/api/flex_promotions/rEs1')
        .reply(200, single(resource('flex_promotions', 'rEs1')))
        .patch('/api/flex_promotions/rEs1', (body) => body.data.attributes._disable === true)
        .reply(200, single(resource('flex_promotions', 'rEs1')))
    })
    .stdout()
    .command(['flex_promotion:disable', 'rEs1', ...AUTH])
    .it('sends the _disable trigger', (ctx) => {
      expect(ctx.stdout).to.contain('Action disable executed without errors')
      expect(ctx.stdout).to.contain('rEs1')
    })
})
