// Generated by @commercelayer/cli-generator from gen.config.ts: do not edit by hand.

import type { Trigger } from '../common'


export const triggers: Record<string, Trigger> = {
  restock: {
      action: 'restock',
      trigger: '_restock',
      description: 'Send this attribute if you want to restock the line item.',
    },
}


export type ActionType =
  'restock'
