// Generated by @commercelayer/cli-generator from gen.config.ts: do not edit by hand.
import { expect, test } from '@oclif/test'
import { AUTH, api, resource, single, useMockedApi } from '../../helpers'

describe('sku_option:remove_tags', () => {
  useMockedApi()

  test
    .timeout(15000)
    .do(() => {
      api()
        .get('/api/sku_options/rEs1')
        .reply(200, single(resource('sku_options', 'rEs1')))
        .patch('/api/sku_options/rEs1', (body) => body.data.attributes._remove_tags === true)
        .reply(200, single(resource('sku_options', 'rEs1')))
    })
    .stdout()
    .command(['sku_option:remove_tags', 'rEs1', ...AUTH])
    .it('sends the _remove_tags trigger', (ctx) => {
      expect(ctx.stdout).to.contain('Action remove_tags executed without errors')
      expect(ctx.stdout).to.contain('rEs1')
    })
})
