// Generated by @commercelayer/cli-generator from gen.config.ts: do not edit by hand.
import { runCommand } from '@oclif/test'
import { expect } from 'chai'
import { AUTH, api, resource, single, useMockedApi } from '../../helpers'

describe('external_gateway:reset_circuit', () => {
  useMockedApi()

  it('sends the _reset_circuit trigger', async function () {
    this.timeout(15000)
    api()
      .get('/api/external_gateways/rEs1')
      .reply(200, single(resource('external_gateways', 'rEs1')))
      .patch('/api/external_gateways/rEs1', (body) => body.data.attributes._reset_circuit === true)
      .reply(200, single(resource('external_gateways', 'rEs1')))
    const ctx = await runCommand(['external_gateway:reset_circuit', 'rEs1', ...AUTH])
    if (ctx.error) throw ctx.error
    expect(ctx.stdout).to.contain('Action reset_circuit executed without errors')
    expect(ctx.stdout).to.contain('rEs1')
  })
})
