// Generated by @commercelayer/cli-generator from gen.config.ts: do not edit by hand.
import { runCommand } from '@oclif/test'
import { expect } from 'chai'
import { AUTH, api, resource, single, useMockedApi } from '../../helpers'

describe('return_line_item:restock', () => {
  useMockedApi()

  it('sends the _restock trigger', async function () {
    this.timeout(15000)
    api()
      .get('/api/return_line_items/rEs1')
      .reply(200, single(resource('return_line_items', 'rEs1')))
      .patch('/api/return_line_items/rEs1', (body) => body.data.attributes._restock === true)
      .reply(200, single(resource('return_line_items', 'rEs1')))
    const ctx = await runCommand(['return_line_item:restock', 'rEs1', ...AUTH])
    if (ctx.error) throw ctx.error
    expect(ctx.stdout).to.contain('Action restock executed without errors')
    expect(ctx.stdout).to.contain('rEs1')
  })
})
