// Generated by @commercelayer/cli-generator from gen.config.ts: do not edit by hand.
import { expect, test } from '@oclif/test'
import { AUTH, api, resource, single, useMockedApi } from '../../helpers'

describe('cleanup:interrupt', () => {
  useMockedApi()

  test
    .timeout(15000)
    .do(() => {
      api()
        .get('/api/cleanups/rEs1')
        .reply(200, single(resource('cleanups', 'rEs1')))
        .patch('/api/cleanups/rEs1', (body) => body.data.attributes._interrupt === true)
        .reply(200, single(resource('cleanups', 'rEs1')))
    })
    .stdout()
    .command(['cleanup:interrupt', 'rEs1', ...AUTH])
    .it('sends the _interrupt trigger', (ctx) => {
      expect(ctx.stdout).to.contain('Action interrupt executed without errors')
      expect(ctx.stdout).to.contain('rEs1')
    })
})
