// Generated by @commercelayer/cli-generator from gen.config.ts: do not edit by hand.
import { expect, test } from '@oclif/test'
import { AUTH, api, resource, single, useMockedApi } from '../../helpers'

describe('stock_item:validate', () => {
  useMockedApi()

  test
    .timeout(15000)
    .do(() => {
      api()
        .get('/api/stock_items/rEs1')
        .reply(200, single(resource('stock_items', 'rEs1')))
        .patch('/api/stock_items/rEs1', (body) => body.data.attributes._validate === true)
        .reply(200, single(resource('stock_items', 'rEs1')))
    })
    .stdout()
    .command(['stock_item:validate', 'rEs1', ...AUTH])
    .it('sends the _validate trigger', (ctx) => {
      expect(ctx.stdout).to.contain('Action validate executed without errors')
      expect(ctx.stdout).to.contain('rEs1')
    })
})
