// Generated by @commercelayer/cli-generator from gen.config.ts: do not edit by hand.
import { expect, test } from '@oclif/test'
import { AUTH, api, resource, single, useMockedApi } from '../../helpers'

describe('void:forward', () => {
  useMockedApi()

  test
    .timeout(15000)
    .do(() => {
      api()
        .get('/api/voids/rEs1')
        .reply(200, single(resource('voids', 'rEs1')))
        .patch('/api/voids/rEs1', (body) => body.data.attributes._forward === true)
        .reply(200, single(resource('voids', 'rEs1')))
    })
    .stdout()
    .command(['void:forward', 'rEs1', ...AUTH])
    .it('sends the _forward trigger', (ctx) => {
      expect(ctx.stdout).to.contain('Action forward executed without errors')
      expect(ctx.stdout).to.contain('rEs1')
    })
})
