// Generated by @commercelayer/cli-generator from gen.config.ts: do not edit by hand.
import { runCommand } from '@oclif/test'
import { expect } from 'chai'
import { AUTH, api, resource, single, useMockedApi } from '../../helpers'

describe('customer:cancel_anonymization', () => {
  useMockedApi()

  it('sends the _cancel_anonymization trigger', async function () {
    this.timeout(15000)
    api()
      .get('/api/customers/rEs1')
      .reply(200, single(resource('customers', 'rEs1')))
      .patch('/api/customers/rEs1', (body) => body.data.attributes._cancel_anonymization === true)
      .reply(200, single(resource('customers', 'rEs1')))
    const ctx = await runCommand(['customer:cancel_anonymization', 'rEs1', ...AUTH])
    if (ctx.error) throw ctx.error
    expect(ctx.stdout).to.contain('Action cancel_anonymization executed without errors')
    expect(ctx.stdout).to.contain('rEs1')
  })
})
