// Generated by @commercelayer/cli-generator from gen.config.ts: do not edit by hand.
import { runCommand } from '@oclif/test'
import { expect } from 'chai'
import { AUTH, api, resource, single, useMockedApi } from '../../helpers'

describe('export:interrupt', () => {
  useMockedApi()

  it('sends the _interrupt trigger', async function () {
    this.timeout(15000)
    api()
      .get('/api/exports/rEs1')
      .reply(200, single(resource('exports', 'rEs1')))
      .patch('/api/exports/rEs1', (body) => body.data.attributes._interrupt === true)
      .reply(200, single(resource('exports', 'rEs1')))
    const ctx = await runCommand(['export:interrupt', 'rEs1', ...AUTH])
    if (ctx.error) throw ctx.error
    expect(ctx.stdout).to.contain('Action interrupt executed without errors')
    expect(ctx.stdout).to.contain('rEs1')
  })
})
