// Generated by @commercelayer/cli-generator from gen.config.ts: do not edit by hand.
import { expect, test } from '@oclif/test'
import { AUTH, api, resource, single, useMockedApi } from '../../helpers'

describe('export:start', () => {
  useMockedApi()

  test
    .timeout(15000)
    .do(() => {
      api()
        .get('/api/exports/rEs1')
        .reply(200, single(resource('exports', 'rEs1')))
        .patch('/api/exports/rEs1', (body) => body.data.attributes._start === true)
        .reply(200, single(resource('exports', 'rEs1')))
    })
    .stdout()
    .command(['export:start', 'rEs1', ...AUTH])
    .it('sends the _start trigger', (ctx) => {
      expect(ctx.stdout).to.contain('Action start executed without errors')
      expect(ctx.stdout).to.contain('rEs1')
    })
})
