// Generated by @commercelayer/cli-generator from gen.config.ts: do not edit by hand.
import { expect, test } from '@oclif/test'
import { AUTH, api, resource, single, useMockedApi } from '../../helpers'

describe('checkout_com_payment:authorize', () => {
  useMockedApi()

  test
    .timeout(15000)
    .do(() => {
      api()
        .get('/api/checkout_com_payments/rEs1')
        .reply(200, single(resource('checkout_com_payments', 'rEs1')))
        .patch('/api/checkout_com_payments/rEs1', (body) => body.data.attributes._authorize === true)
        .reply(200, single(resource('checkout_com_payments', 'rEs1')))
    })
    .stdout()
    .command(['checkout_com_payment:authorize', 'rEs1', ...AUTH])
    .it('sends the _authorize trigger', (ctx) => {
      expect(ctx.stdout).to.contain('Action authorize executed without errors')
      expect(ctx.stdout).to.contain('rEs1')
    })
})
