// Generated by @commercelayer/cli-generator from gen.config.ts: do not edit by hand.
import { expect, test } from '@oclif/test'
import { AUTH, api, resource, single, useMockedApi } from '../../helpers'

describe('satispay_payment:refresh', () => {
  useMockedApi()

  test
    .timeout(15000)
    .do(() => {
      api()
        .get('/api/satispay_payments/rEs1')
        .reply(200, single(resource('satispay_payments', 'rEs1')))
        .patch('/api/satispay_payments/rEs1', (body) => body.data.attributes._refresh === true)
        .reply(200, single(resource('satispay_payments', 'rEs1')))
    })
    .stdout()
    .command(['satispay_payment:refresh', 'rEs1', ...AUTH])
    .it('sends the _refresh trigger', (ctx) => {
      expect(ctx.stdout).to.contain('Action refresh executed without errors')
      expect(ctx.stdout).to.contain('rEs1')
    })
})
