// Generated by @commercelayer/cli-generator from gen.config.ts: do not edit by hand.
import { expect, test } from '@oclif/test'
import { AUTH, api, resource, single, useMockedApi } from '../../helpers'

describe('order_subscription:activate', () => {
  useMockedApi()

  test
    .timeout(15000)
    .do(() => {
      api()
        .get('/api/order_subscriptions/rEs1')
        .reply(200, single(resource('order_subscriptions', 'rEs1')))
        .patch('/api/order_subscriptions/rEs1', (body) => body.data.attributes._activate === true)
        .reply(200, single(resource('order_subscriptions', 'rEs1')))
    })
    .stdout()
    .command(['order_subscription:activate', 'rEs1', ...AUTH])
    .it('sends the _activate trigger', (ctx) => {
      expect(ctx.stdout).to.contain('Action activate executed without errors')
      expect(ctx.stdout).to.contain('rEs1')
    })
})
