// Generated by @commercelayer/cli-generator from gen.config.ts: do not edit by hand.
import { runCommand } from '@oclif/test'
import { expect } from 'chai'
import { AUTH, api, resource, single, useMockedApi } from '../../helpers'

describe('order_subscription:deactivate', () => {
  useMockedApi()

  it('sends the _deactivate trigger', async function () {
    this.timeout(15000)
    api()
      .get('/api/order_subscriptions/rEs1')
      .reply(200, single(resource('order_subscriptions', 'rEs1')))
      .patch('/api/order_subscriptions/rEs1', (body) => body.data.attributes._deactivate === true)
      .reply(200, single(resource('order_subscriptions', 'rEs1')))
    const ctx = await runCommand(['order_subscription:deactivate', 'rEs1', ...AUTH])
    if (ctx.error) throw ctx.error
    expect(ctx.stdout).to.contain('Action deactivate executed without errors')
    expect(ctx.stdout).to.contain('rEs1')
  })
})
