// Generated by @commercelayer/cli-generator from gen.config.ts: do not edit by hand.
import { runCommand } from '@oclif/test'
import { expect } from 'chai'
import { AUTH, api, resource, single, useMockedApi } from '../../helpers'

describe('order:create_subscriptions', () => {
  useMockedApi()

  it('sends the _create_subscriptions trigger', async function () {
    this.timeout(15000)
    api()
      .get('/api/orders/rEs1')
      .reply(200, single(resource('orders', 'rEs1')))
      .patch('/api/orders/rEs1', (body) => body.data.attributes._create_subscriptions === true)
      .reply(200, single(resource('orders', 'rEs1')))
    const ctx = await runCommand(['order:create_subscriptions', 'rEs1', ...AUTH])
    if (ctx.error) throw ctx.error
    expect(ctx.stdout).to.contain('Action create_subscriptions executed without errors')
    expect(ctx.stdout).to.contain('rEs1')
  })
})
