// Generated by @commercelayer/cli-generator from gen.config.ts: do not edit by hand.
import { runCommand } from '@oclif/test'
import { expect } from 'chai'
import { AUTH, api, resource, single, useMockedApi } from '../../helpers'

describe('order:customer_payment_source_id', () => {
  useMockedApi()

  it('sends the _customer_payment_source_id trigger', async function () {
    this.timeout(15000)
    api()
      .get('/api/orders/rEs1')
      .reply(200, single(resource('orders', 'rEs1')))
      .patch('/api/orders/rEs1', (body) => body.data.attributes._customer_payment_source_id === 'vAlUe1')
      .reply(200, single(resource('orders', 'rEs1')))
    const ctx = await runCommand(['order:customer_payment_source_id', 'rEs1', ...AUTH, '-v', 'vAlUe1'])
    if (ctx.error) throw ctx.error
    expect(ctx.stdout).to.contain('Action customer_payment_source_id executed without errors')
    expect(ctx.stdout).to.contain('rEs1')
  })
})
