// Generated by @commercelayer/cli-generator from gen.config.ts: do not edit by hand.
import { expect, test } from '@oclif/test'
import { AUTH, api, resource, single, useMockedApi } from '../../helpers'

describe('order:customer_payment_source_id', () => {
  useMockedApi()

  test
    .timeout(15000)
    .do(() => {
      api()
        .get('/api/orders/rEs1')
        .reply(200, single(resource('orders', 'rEs1')))
        .patch('/api/orders/rEs1', (body) => body.data.attributes._customer_payment_source_id === 'vAlUe1')
        .reply(200, single(resource('orders', 'rEs1')))
    })
    .stdout()
    .command(['order:customer_payment_source_id', 'rEs1', ...AUTH, '-v', 'vAlUe1'])
    .it('sends the _customer_payment_source_id trigger', (ctx) => {
      expect(ctx.stdout).to.contain('Action customer_payment_source_id executed without errors')
      expect(ctx.stdout).to.contain('rEs1')
    })
})
