// Generated by @commercelayer/cli-generator from gen.config.ts: do not edit by hand.
import { runCommand } from '@oclif/test'
import { expect } from 'chai'
import { AUTH, api, resource, single, useMockedApi } from '../../helpers'

describe('order:refund_invoice', () => {
  useMockedApi()

  it('sends the _refund_invoice trigger', async function () {
    this.timeout(15000)
    api()
      .get('/api/orders/rEs1')
      .reply(200, single(resource('orders', 'rEs1')))
      .patch('/api/orders/rEs1', (body) => body.data.attributes._refund_invoice === true)
      .reply(200, single(resource('orders', 'rEs1')))
    const ctx = await runCommand(['order:refund_invoice', 'rEs1', ...AUTH])
    if (ctx.error) throw ctx.error
    expect(ctx.stdout).to.contain('Action refund_invoice executed without errors')
    expect(ctx.stdout).to.contain('rEs1')
  })
})
