// Generated by @commercelayer/cli-generator from gen.config.ts: do not edit by hand.
import { expect, test } from '@oclif/test'
import { AUTH, api, resource, single, useMockedApi } from '../../helpers'

describe('order:save_payment_source_to_customer_wallet', () => {
  useMockedApi()

  test
    .timeout(15000)
    .do(() => {
      api()
        .get('/api/orders/rEs1')
        .reply(200, single(resource('orders', 'rEs1')))
        .patch('/api/orders/rEs1', (body) => body.data.attributes._save_payment_source_to_customer_wallet === true)
        .reply(200, single(resource('orders', 'rEs1')))
    })
    .stdout()
    .command(['order:save_payment_source_to_customer_wallet', 'rEs1', ...AUTH])
    .it('sends the _save_payment_source_to_customer_wallet trigger', (ctx) => {
      expect(ctx.stdout).to.contain('Action save_payment_source_to_customer_wallet executed without errors')
      expect(ctx.stdout).to.contain('rEs1')
    })
})
