// Generated by @commercelayer/cli-generator from gen.config.ts: do not edit by hand.
import { runCommand } from '@oclif/test'
import { expect } from 'chai'
import { AUTH, api, resource, single, useMockedApi } from '../../helpers'

describe('order:save_billing_address_to_customer_address_book', () => {
  useMockedApi()

  it('sends the _save_billing_address_to_customer_address_book trigger', async function () {
    this.timeout(15000)
    api()
      .get('/api/orders/rEs1')
      .reply(200, single(resource('orders', 'rEs1')))
      .patch('/api/orders/rEs1', (body) => body.data.attributes._save_billing_address_to_customer_address_book === true)
      .reply(200, single(resource('orders', 'rEs1')))
    const ctx = await runCommand(['order:save_billing_address_to_customer_address_book', 'rEs1', ...AUTH])
    if (ctx.error) throw ctx.error
    expect(ctx.stdout).to.contain('Action save_billing_address_to_customer_address_book executed without errors')
    expect(ctx.stdout).to.contain('rEs1')
  })
})
