// Generated by @commercelayer/cli-generator from gen.config.ts: do not edit by hand.
import { expect, test } from '@oclif/test'
import { AUTH, api, resource, single, useMockedApi } from '../../helpers'

describe('external_tax_calculator:regenerate_shared_secret', () => {
  useMockedApi()

  test
    .timeout(15000)
    .do(() => {
      api()
        .get('/api/external_tax_calculators/rEs1')
        .reply(200, single(resource('external_tax_calculators', 'rEs1')))
        .patch('/api/external_tax_calculators/rEs1', (body) => body.data.attributes._regenerate_shared_secret === true)
        .reply(200, single(resource('external_tax_calculators', 'rEs1')))
    })
    .stdout()
    .command(['external_tax_calculator:regenerate_shared_secret', 'rEs1', ...AUTH])
    .it('sends the _regenerate_shared_secret trigger', (ctx) => {
      expect(ctx.stdout).to.contain('Action regenerate_shared_secret executed without errors')
      expect(ctx.stdout).to.contain('rEs1')
    })
})
