/**
 * The per-resource index commands (e.g. `order <id>`) ask which trigger to
 * execute. Hand-written: test/commands is regenerated by gen.config.ts.
 */
import { expect, test } from '@oclif/test'
import inquirer from 'inquirer'
import { AUTH, api, resource, single, useMockedApi } from '../helpers'

describe('<resource> index commands', () => {
  useMockedApi()

  const prompt = inquirer.prompt
  afterEach(() => {
    inquirer.prompt = prompt
  })

  test
    .do(() => {
      inquirer.prompt = (async () => ({ trigger: 'refresh' })) as unknown as typeof inquirer.prompt
      api()
        .get('/api/orders/oRd1')
        .reply(200, single(resource('orders', 'oRd1')))
        .patch('/api/orders/oRd1', (body) => body.data.attributes._refresh === true)
        .reply(200, single(resource('orders', 'oRd1')))
    })
    .stdout()
    .command(['order', 'oRd1', ...AUTH])
    .it('executes the trigger picked from the list', (ctx) => {
      expect(ctx.stdout).to.contain('Action refresh executed without errors')
    })
})
