/**
 * The per-resource index commands (e.g. `order <id>`) ask which trigger to
 * execute. Hand-written: test/commands is regenerated by gen.config.ts.
 */
import { runCommand } from '@oclif/test'
import { expect } from 'chai'
import inquirer from 'inquirer'
import { AUTH, api, resource, single, useMockedApi } from '../helpers'

describe('<resource> index commands', () => {
  useMockedApi()

  const prompt = inquirer.prompt
  afterEach(() => {
    inquirer.prompt = prompt
  })

  it('executes the trigger picked from the list', async () => {
    inquirer.prompt = (async () => ({ trigger: 'refresh' })) as unknown as typeof inquirer.prompt
    api()
      .get('/api/orders/oRd1')
      .reply(200, single(resource('orders', 'oRd1')))
      .patch('/api/orders/oRd1', (body) => body.data.attributes._refresh === true)
      .reply(200, single(resource('orders', 'oRd1')))
    const ctx = await runCommand(['order', 'oRd1', ...AUTH])
    if (ctx.error) throw ctx.error
    expect(ctx.stdout).to.contain('Action refresh executed without errors')
  })
})
