/**
 * What a generator gets to work with: the snapshot data and a few file
 * helpers, all relative to the plugin folder.
 */
import { existsSync, mkdirSync, readdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'

export type Context = {
  /** The data `schema.extract` produced, read back from the snapshot */
  snapshot: any
  /** Reads `<templatesDir>/<name>.tpl` */
  template: (name: string) => string
  write: (path: string, content: string) => void
  mkdir: (path: string) => void
  /** Empties a folder, except the entries listed in `keep` */
  clean: (dir: string, keep?: string[]) => void
  log: (message: string) => void
}

export const createContext = (snapshot: unknown, templatesDir = 'gen/templates'): Context => ({
  snapshot,
  template: (name) => readFileSync(join(templatesDir, name.endsWith('.tpl') ? name : `${name}.tpl`), { encoding: 'utf-8' }),
  write: (path, content) => {
    mkdirSync(dirname(path), { recursive: true })
    writeFileSync(path, content, { encoding: 'utf-8' })
  },
  mkdir: (path) => {
    mkdirSync(path, { recursive: true })
  },
  clean: (dir, keep = []) => {
    if (!existsSync(dir)) return
    for (const entry of readdirSync(dir)) if (!keep.includes(entry)) rmSync(join(dir, entry), { recursive: true, force: true })
  },
  log: (message) => {
    console.log(message)
  },
})

export const GENERATED_HEADER = '// Generated by @commercelayer/cli-generator from gen.config.ts: do not edit by hand.'

/** Marks a generated TypeScript file */
export const generated = (content: string): string => `${GENERATED_HEADER}\n${content}`

/**
 * Replaces `##__NAME__##` placeholders. `all` values replace every occurrence,
 * `first` values only the first one. Replacements are literal (no `$&`
 * patterns), so API descriptions can't corrupt the output.
 */
export const render = (template: string, all: Record<string, string>, first: Record<string, string> = {}): string => {
  let out = template
  for (const [key, value] of Object.entries(all)) out = out.split(`##__${key}__##`).join(value)
  for (const [key, value] of Object.entries(first)) out = out.replace(`##__${key}__##`, () => value)
  return out
}
