// Generated by @commercelayer/cli-generator from gen.config.ts: do not edit by hand.
import { runCommand } from '@oclif/test'
import { expect } from 'chai'
import { AUTH, api, resource, single, useMockedApi } from '../../helpers'

describe('vertex_account:refresh_token', () => {
  useMockedApi()

  it('sends the _refresh_token trigger', async function () {
    this.timeout(15000)
    api()
      .get('/api/vertex_accounts/rEs1')
      .reply(200, single(resource('vertex_accounts', 'rEs1')))
      .patch('/api/vertex_accounts/rEs1', (body) => body.data.attributes._refresh_token === true)
      .reply(200, single(resource('vertex_accounts', 'rEs1')))
    const ctx = await runCommand(['vertex_account:refresh_token', 'rEs1', ...AUTH])
    if (ctx.error) throw ctx.error
    expect(ctx.stdout).to.contain('Action refresh_token executed without errors')
    expect(ctx.stdout).to.contain('rEs1')
  })
})
