// Generated by @commercelayer/cli-generator from gen.config.ts: do not edit by hand.
import { runCommand } from '@oclif/test'
import { expect } from 'chai'
import { AUTH, api, resource, single, useMockedApi } from '../../helpers'

describe('customer_password_reset:reset_password_token', () => {
  useMockedApi()

  it('sends the _reset_password_token trigger', async function () {
    this.timeout(15000)
    api()
      .get('/api/customer_password_resets/rEs1')
      .reply(200, single(resource('customer_password_resets', 'rEs1')))
      .patch('/api/customer_password_resets/rEs1', (body) => body.data.attributes._reset_password_token === true)
      .reply(200, single(resource('customer_password_resets', 'rEs1')))
    const ctx = await runCommand(['customer_password_reset:reset_password_token', 'rEs1', ...AUTH])
    if (ctx.error) throw ctx.error
    expect(ctx.stdout).to.contain('Action reset_password_token executed without errors')
    expect(ctx.stdout).to.contain('rEs1')
  })
})
