/**
 * Generates .github/labeler.yml: one `pkg:<dir>` label per package, applied
 * from the files a PR touches, so a PR shows at a glance which packages it
 * changes. Removes the GitHub release-notes configs (.github/release-<dir>.yml)
 * once generated: the notes now come from the commits (`cl-release notes`).
 */
import { existsSync, readdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'
import { parse } from '../args.ts'
import { type Package, publicPackages } from '../workspace.ts'

const USAGE = `Usage: cl-release labels [--check]
  --check  exit 1 if the committed files are out of date (used in CI)`

const GITHUB = '.github'
const HEADER = '# Generated by `pnpm release:config` (cl-release labels) — do not edit by hand.\n'

export const labelerConfig = (packages: Pick<Package, 'dir' | 'path'>[]): string =>
  HEADER + packages.map((pkg) => `\n'pkg:${pkg.dir}':\n  - changed-files:\n      - any-glob-to-any-file:\n          - '${pkg.path}/**'\n`).join('')

export const run = (args: string[]): void => {
  const { values } = parse(args, { check: { type: 'boolean' } }, USAGE)
  const packages = publicPackages()

  const files = new Map([[join(GITHUB, 'labeler.yml'), labelerConfig(packages)]])
  // The release-notes configs of GitHub's generated notes, no longer used
  const stale = readdirSync(GITHUB).filter((f) => /^release-.+\.yml$/.test(f) && !files.has(join(GITHUB, f)))
  const outdated = [...files].filter(([path, content]) => !existsSync(path) || readFileSync(path, 'utf8') !== content).map(([path]) => path)

  if (values.check) {
    const problems = [...outdated, ...stale.map((f) => join(GITHUB, f))]
    if (problems.length > 0) {
      console.error(`Release config is out of date: ${problems.join(', ')}\nRun \`pnpm release:config\` and commit the result.`)
      process.exit(1)
    }
    console.log(`Release config is up to date (${packages.length} packages).`)
  } else {
    for (const path of outdated) writeFileSync(path, files.get(path) as string)
    for (const f of stale) rmSync(join(GITHUB, f))
    console.log(`Wrote ${outdated.length} file(s), removed ${stale.length}, ${packages.length} packages.`)
  }
}
