// Generated by @commercelayer/cli-generator from gen.config.ts: do not edit by hand.
import { runCommand } from '@oclif/test'
import { expect } from 'chai'
import { AUTH, api, resource, single, useMockedApi } from '../../helpers'

describe('authorization:capture', () => {
  useMockedApi()

  it('sends the _capture trigger', async function () {
    this.timeout(15000)
    api()
      .get('/api/authorizations/rEs1')
      .reply(200, single(resource('authorizations', 'rEs1')))
      .patch('/api/authorizations/rEs1', (body) => body.data.attributes._capture === true)
      .reply(200, single(resource('authorizations', 'rEs1')))
    const ctx = await runCommand(['authorization:capture', 'rEs1', ...AUTH])
    if (ctx.error) throw ctx.error
    expect(ctx.stdout).to.contain('Action capture executed without errors')
    expect(ctx.stdout).to.contain('rEs1')
  })
})
