// Generated by @commercelayer/cli-generator from gen.config.ts: do not edit by hand.
import { runCommand } from '@oclif/test'
import { expect } from 'chai'
import { AUTH, api, resource, single, useMockedApi } from '../../helpers'

describe('refund:forward', () => {
  useMockedApi()

  it('sends the _forward trigger', async function () {
    this.timeout(15000)
    api()
      .get('/api/refunds/rEs1')
      .reply(200, single(resource('refunds', 'rEs1')))
      .patch('/api/refunds/rEs1', (body) => body.data.attributes._forward === true)
      .reply(200, single(resource('refunds', 'rEs1')))
    const ctx = await runCommand(['refund:forward', 'rEs1', ...AUTH])
    if (ctx.error) throw ctx.error
    expect(ctx.stdout).to.contain('Action forward executed without errors')
    expect(ctx.stdout).to.contain('rEs1')
  })
})
