// Generated by @commercelayer/cli-generator from gen.config.ts: do not edit by hand.
import { runCommand } from '@oclif/test'
import { expect } from 'chai'
import { AUTH, api, resource, single, useMockedApi } from '../../helpers'

describe('easypost_pickup:purchase', () => {
  useMockedApi()

  it('sends the _purchase trigger', async function () {
    this.timeout(15000)
    api()
      .get('/api/easypost_pickups/rEs1')
      .reply(200, single(resource('easypost_pickups', 'rEs1')))
      .patch('/api/easypost_pickups/rEs1', (body) => body.data.attributes._purchase === true)
      .reply(200, single(resource('easypost_pickups', 'rEs1')))
    const ctx = await runCommand(['easypost_pickup:purchase', 'rEs1', ...AUTH])
    if (ctx.error) throw ctx.error
    expect(ctx.stdout).to.contain('Action purchase executed without errors')
    expect(ctx.stdout).to.contain('rEs1')
  })
})
