// Generated by @commercelayer/cli-generator from gen.config.ts: do not edit by hand.
import { expect, test } from '@oclif/test'
import { AUTH, api, resource, single, useMockedApi } from '../../helpers'

describe('stripe_payment:update', () => {
  useMockedApi()

  test
    .timeout(15000)
    .do(() => {
      api()
        .get('/api/stripe_payments/rEs1')
        .reply(200, single(resource('stripe_payments', 'rEs1')))
        .patch('/api/stripe_payments/rEs1', (body) => body.data.attributes._update === true)
        .reply(200, single(resource('stripe_payments', 'rEs1')))
    })
    .stdout()
    .command(['stripe_payment:update', 'rEs1', ...AUTH])
    .it('sends the _update trigger', (ctx) => {
      expect(ctx.stdout).to.contain('Action update executed without errors')
      expect(ctx.stdout).to.contain('rEs1')
    })
})
