// Generated by @commercelayer/cli-generator from gen.config.ts: do not edit by hand.
import { runCommand } from '@oclif/test'
import { expect } from 'chai'
import { AUTH, api, resource, single, useMockedApi } from '../../helpers'

describe('stripe_payment:update', () => {
  useMockedApi()

  it('sends the _update trigger', async function () {
    this.timeout(15000)
    api()
      .get('/api/stripe_payments/rEs1')
      .reply(200, single(resource('stripe_payments', 'rEs1')))
      .patch('/api/stripe_payments/rEs1', (body) => body.data.attributes._update === true)
      .reply(200, single(resource('stripe_payments', 'rEs1')))
    const ctx = await runCommand(['stripe_payment:update', 'rEs1', ...AUTH])
    if (ctx.error) throw ctx.error
    expect(ctx.stdout).to.contain('Action update executed without errors')
    expect(ctx.stdout).to.contain('rEs1')
  })
})
