// Generated by @commercelayer/cli-generator from gen.config.ts: do not edit by hand.
import { runCommand } from '@oclif/test'
import { expect } from 'chai'
import { AUTH, api, resource, single, useMockedApi } from '../../helpers'

describe('webhook:enable', () => {
  useMockedApi()

  it('sends the _enable trigger', async function () {
    this.timeout(15000)
    api()
      .get('/api/webhooks/rEs1')
      .reply(200, single(resource('webhooks', 'rEs1')))
      .patch('/api/webhooks/rEs1', (body) => body.data.attributes._enable === true)
      .reply(200, single(resource('webhooks', 'rEs1')))
    const ctx = await runCommand(['webhook:enable', 'rEs1', ...AUTH])
    if (ctx.error) throw ctx.error
    expect(ctx.stdout).to.contain('Action enable executed without errors')
    expect(ctx.stdout).to.contain('rEs1')
  })
})
