// Generated by @commercelayer/cli-generator from gen.config.ts: do not edit by hand.
import { runCommand } from '@oclif/test'
import { expect } from 'chai'
import { AUTH, api, resource, single, useMockedApi } from '../../helpers'

describe('line_item:external_price', () => {
  useMockedApi()

  it('sends the _external_price trigger', async function () {
    this.timeout(15000)
    api()
      .get('/api/line_items/rEs1')
      .reply(200, single(resource('line_items', 'rEs1')))
      .patch('/api/line_items/rEs1', (body) => body.data.attributes._external_price === true)
      .reply(200, single(resource('line_items', 'rEs1')))
    const ctx = await runCommand(['line_item:external_price', 'rEs1', ...AUTH])
    if (ctx.error) throw ctx.error
    expect(ctx.stdout).to.contain('Action external_price executed without errors')
    expect(ctx.stdout).to.contain('rEs1')
  })
})
