// Generated by @commercelayer/cli-generator from gen.config.ts: do not edit by hand.
import { expect, test } from '@oclif/test'
import { AUTH, api, resource, single, useMockedApi } from '../../helpers'

describe('line_item:external_price', () => {
  useMockedApi()

  test
    .timeout(15000)
    .do(() => {
      api()
        .get('/api/line_items/rEs1')
        .reply(200, single(resource('line_items', 'rEs1')))
        .patch('/api/line_items/rEs1', (body) => body.data.attributes._external_price === true)
        .reply(200, single(resource('line_items', 'rEs1')))
    })
    .stdout()
    .command(['line_item:external_price', 'rEs1', ...AUTH])
    .it('sends the _external_price trigger', (ctx) => {
      expect(ctx.stdout).to.contain('Action external_price executed without errors')
      expect(ctx.stdout).to.contain('rEs1')
    })
})
