// Generated by @commercelayer/cli-generator from gen.config.ts: do not edit by hand.
import { runCommand } from '@oclif/test'
import { expect } from 'chai'
import { AUTH, api, resource, single, useMockedApi } from '../../helpers'

describe('line_item:reset_restocked_quantity', () => {
  useMockedApi()

  it('sends the _reset_restocked_quantity trigger', async function () {
    this.timeout(15000)
    api()
      .get('/api/line_items/rEs1')
      .reply(200, single(resource('line_items', 'rEs1')))
      .patch('/api/line_items/rEs1', (body) => body.data.attributes._reset_restocked_quantity === true)
      .reply(200, single(resource('line_items', 'rEs1')))
    const ctx = await runCommand(['line_item:reset_restocked_quantity', 'rEs1', ...AUTH])
    if (ctx.error) throw ctx.error
    expect(ctx.stdout).to.contain('Action reset_restocked_quantity executed without errors')
    expect(ctx.stdout).to.contain('rEs1')
  })
})
