// Generated by @commercelayer/cli-generator from gen.config.ts: do not edit by hand.
import { expect, test } from '@oclif/test'
import { AUTH, api, resource, single, useMockedApi } from '../../helpers'

describe('line_item:reserve_stock', () => {
  useMockedApi()

  test
    .timeout(15000)
    .do(() => {
      api()
        .get('/api/line_items/rEs1')
        .reply(200, single(resource('line_items', 'rEs1')))
        .patch('/api/line_items/rEs1', (body) => body.data.attributes._reserve_stock === true)
        .reply(200, single(resource('line_items', 'rEs1')))
    })
    .stdout()
    .command(['line_item:reserve_stock', 'rEs1', ...AUTH])
    .it('sends the _reserve_stock trigger', (ctx) => {
      expect(ctx.stdout).to.contain('Action reserve_stock executed without errors')
      expect(ctx.stdout).to.contain('rEs1')
    })
})
